# Generated by Django 2.2.12 on 2020-06-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_test_ha2'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ha3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
