# Generated by Django 2.2.12 on 2020-06-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_test_ha3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=256)),
            ],
        ),
    ]
